#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaekwondoSkor.Classes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="taekwondo_skor")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKayitlar(Kayitlar instance);
    partial void UpdateKayitlar(Kayitlar instance);
    partial void DeleteKayitlar(Kayitlar instance);
    partial void InsertMaclar(Maclar instance);
    partial void UpdateMaclar(Maclar instance);
    partial void DeleteMaclar(Maclar instance);
    partial void InsertSporcular(Sporcular instance);
    partial void UpdateSporcular(Sporcular instance);
    partial void DeleteSporcular(Sporcular instance);
    partial void InsertGlobal_Veriler(Global_Veriler instance);
    partial void UpdateGlobal_Veriler(Global_Veriler instance);
    partial void DeleteGlobal_Veriler(Global_Veriler instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::TaekwondoSkor.Properties.Settings.Default.taekwondo_skorConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kayitlar> Kayitlar
		{
			get
			{
				return this.GetTable<Kayitlar>();
			}
		}
		
		public System.Data.Linq.Table<Maclar> Maclar
		{
			get
			{
				return this.GetTable<Maclar>();
			}
		}
		
		public System.Data.Linq.Table<Sporcular> Sporcular
		{
			get
			{
				return this.GetTable<Sporcular>();
			}
		}
		
		public System.Data.Linq.Table<Global_Veriler> Global_Veriler
		{
			get
			{
				return this.GetTable<Global_Veriler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kayitlar")]
	public partial class Kayitlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _tarih;
		
		private string _islem;
		
		private System.Nullable<int> _macid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    partial void OnislemChanging(string value);
    partial void OnislemChanged();
    partial void OnmacidChanging(System.Nullable<int> value);
    partial void OnmacidChanged();
    #endregion
		
		public Kayitlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_islem", DbType="NVarChar(300)")]
		public string islem
		{
			get
			{
				return this._islem;
			}
			set
			{
				if ((this._islem != value))
				{
					this.OnislemChanging(value);
					this.SendPropertyChanging();
					this._islem = value;
					this.SendPropertyChanged("islem");
					this.OnislemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macid", DbType="Int")]
		public System.Nullable<int> macid
		{
			get
			{
				return this._macid;
			}
			set
			{
				if ((this._macid != value))
				{
					this.OnmacidChanging(value);
					this.SendPropertyChanging();
					this._macid = value;
					this.SendPropertyChanged("macid");
					this.OnmacidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maclar")]
	public partial class Maclar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _kisi1;
		
		private string _kisi2;
		
		private System.Nullable<System.DateTime> _tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onkisi1Changing(string value);
    partial void Onkisi1Changed();
    partial void Onkisi2Changing(string value);
    partial void Onkisi2Changed();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    #endregion
		
		public Maclar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kisi1", DbType="NVarChar(100)")]
		public string kisi1
		{
			get
			{
				return this._kisi1;
			}
			set
			{
				if ((this._kisi1 != value))
				{
					this.Onkisi1Changing(value);
					this.SendPropertyChanging();
					this._kisi1 = value;
					this.SendPropertyChanged("kisi1");
					this.Onkisi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kisi2", DbType="NVarChar(100)")]
		public string kisi2
		{
			get
			{
				return this._kisi2;
			}
			set
			{
				if ((this._kisi2 != value))
				{
					this.Onkisi2Changing(value);
					this.SendPropertyChanging();
					this._kisi2 = value;
					this.SendPropertyChanged("kisi2");
					this.Onkisi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sporcular")]
	public partial class Sporcular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public Sporcular()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(100)")]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Global_Veriler")]
	public partial class Global_Veriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mavirenk;
		
		private string _kirmizirenk;
		
		private System.TimeSpan _arasuresi;
		
		private int _maxpuansayi;
		
		private bool _maxpuan;
		
		private int _raundsayisi;
		
		private bool _onikifarkpuani;
		
		private bool _sureartan;
		
		private bool _timeoutsureartan;
		
		private int _vucutpuani;
		
		private int _kafapuani;
		
		private System.Nullable<System.TimeSpan> _raundsuresi;
		
		private string _skorrenk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmavirenkChanging(string value);
    partial void OnmavirenkChanged();
    partial void OnkirmizirenkChanging(string value);
    partial void OnkirmizirenkChanged();
    partial void OnarasuresiChanging(System.TimeSpan value);
    partial void OnarasuresiChanged();
    partial void OnmaxpuansayiChanging(int value);
    partial void OnmaxpuansayiChanged();
    partial void OnmaxpuanChanging(bool value);
    partial void OnmaxpuanChanged();
    partial void OnraundsayisiChanging(int value);
    partial void OnraundsayisiChanged();
    partial void OnonikifarkpuaniChanging(bool value);
    partial void OnonikifarkpuaniChanged();
    partial void OnsureartanChanging(bool value);
    partial void OnsureartanChanged();
    partial void OntimeoutsureartanChanging(bool value);
    partial void OntimeoutsureartanChanged();
    partial void OnvucutpuaniChanging(int value);
    partial void OnvucutpuaniChanged();
    partial void OnkafapuaniChanging(int value);
    partial void OnkafapuaniChanged();
    partial void OnraundsuresiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnraundsuresiChanged();
    partial void OnskorrenkChanging(string value);
    partial void OnskorrenkChanged();
    #endregion
		
		public Global_Veriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavirenk", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mavirenk
		{
			get
			{
				return this._mavirenk;
			}
			set
			{
				if ((this._mavirenk != value))
				{
					this.OnmavirenkChanging(value);
					this.SendPropertyChanging();
					this._mavirenk = value;
					this.SendPropertyChanged("mavirenk");
					this.OnmavirenkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kirmizirenk", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kirmizirenk
		{
			get
			{
				return this._kirmizirenk;
			}
			set
			{
				if ((this._kirmizirenk != value))
				{
					this.OnkirmizirenkChanging(value);
					this.SendPropertyChanging();
					this._kirmizirenk = value;
					this.SendPropertyChanged("kirmizirenk");
					this.OnkirmizirenkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arasuresi", DbType="Time NOT NULL")]
		public System.TimeSpan arasuresi
		{
			get
			{
				return this._arasuresi;
			}
			set
			{
				if ((this._arasuresi != value))
				{
					this.OnarasuresiChanging(value);
					this.SendPropertyChanging();
					this._arasuresi = value;
					this.SendPropertyChanged("arasuresi");
					this.OnarasuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxpuansayi", DbType="Int NOT NULL")]
		public int maxpuansayi
		{
			get
			{
				return this._maxpuansayi;
			}
			set
			{
				if ((this._maxpuansayi != value))
				{
					this.OnmaxpuansayiChanging(value);
					this.SendPropertyChanging();
					this._maxpuansayi = value;
					this.SendPropertyChanged("maxpuansayi");
					this.OnmaxpuansayiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxpuan", DbType="Bit NOT NULL")]
		public bool maxpuan
		{
			get
			{
				return this._maxpuan;
			}
			set
			{
				if ((this._maxpuan != value))
				{
					this.OnmaxpuanChanging(value);
					this.SendPropertyChanging();
					this._maxpuan = value;
					this.SendPropertyChanged("maxpuan");
					this.OnmaxpuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raundsayisi", DbType="Int NOT NULL")]
		public int raundsayisi
		{
			get
			{
				return this._raundsayisi;
			}
			set
			{
				if ((this._raundsayisi != value))
				{
					this.OnraundsayisiChanging(value);
					this.SendPropertyChanging();
					this._raundsayisi = value;
					this.SendPropertyChanged("raundsayisi");
					this.OnraundsayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onikifarkpuani", DbType="Bit NOT NULL")]
		public bool onikifarkpuani
		{
			get
			{
				return this._onikifarkpuani;
			}
			set
			{
				if ((this._onikifarkpuani != value))
				{
					this.OnonikifarkpuaniChanging(value);
					this.SendPropertyChanging();
					this._onikifarkpuani = value;
					this.SendPropertyChanged("onikifarkpuani");
					this.OnonikifarkpuaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sureartan", DbType="Bit NOT NULL")]
		public bool sureartan
		{
			get
			{
				return this._sureartan;
			}
			set
			{
				if ((this._sureartan != value))
				{
					this.OnsureartanChanging(value);
					this.SendPropertyChanging();
					this._sureartan = value;
					this.SendPropertyChanged("sureartan");
					this.OnsureartanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeoutsureartan", DbType="Bit NOT NULL")]
		public bool timeoutsureartan
		{
			get
			{
				return this._timeoutsureartan;
			}
			set
			{
				if ((this._timeoutsureartan != value))
				{
					this.OntimeoutsureartanChanging(value);
					this.SendPropertyChanging();
					this._timeoutsureartan = value;
					this.SendPropertyChanged("timeoutsureartan");
					this.OntimeoutsureartanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vucutpuani", DbType="Int NOT NULL")]
		public int vucutpuani
		{
			get
			{
				return this._vucutpuani;
			}
			set
			{
				if ((this._vucutpuani != value))
				{
					this.OnvucutpuaniChanging(value);
					this.SendPropertyChanging();
					this._vucutpuani = value;
					this.SendPropertyChanged("vucutpuani");
					this.OnvucutpuaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kafapuani", DbType="Int NOT NULL")]
		public int kafapuani
		{
			get
			{
				return this._kafapuani;
			}
			set
			{
				if ((this._kafapuani != value))
				{
					this.OnkafapuaniChanging(value);
					this.SendPropertyChanging();
					this._kafapuani = value;
					this.SendPropertyChanged("kafapuani");
					this.OnkafapuaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raundsuresi", DbType="Time")]
		public System.Nullable<System.TimeSpan> raundsuresi
		{
			get
			{
				return this._raundsuresi;
			}
			set
			{
				if ((this._raundsuresi != value))
				{
					this.OnraundsuresiChanging(value);
					this.SendPropertyChanging();
					this._raundsuresi = value;
					this.SendPropertyChanged("raundsuresi");
					this.OnraundsuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skorrenk", DbType="VarChar(50)")]
		public string skorrenk
		{
			get
			{
				return this._skorrenk;
			}
			set
			{
				if ((this._skorrenk != value))
				{
					this.OnskorrenkChanging(value);
					this.SendPropertyChanging();
					this._skorrenk = value;
					this.SendPropertyChanged("skorrenk");
					this.OnskorrenkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
